package org.open2jam.export;

import java.nio.ByteBuffer;
import java.nio.ByteOrder;
import java.nio.charset.StandardCharsets;
import java.nio.file.Files;
import java.nio.file.Path;
import java.util.List;
import java.util.zip.ZipEntry;
import java.util.zip.ZipOutputStream;
import org.open2jam.parsers.OjnFixtureFactory;
import org.open2jam.parsers.OsuFixtureFactory;
import org.open2jam.parsers.VosFixtureFactory;

final class MigrationGoldenFixtureFactory {
    private static final String PROVENANCE =
            "self-authored deterministic fixture generated by repository test code";
    private static final String LICENSE = "Artistic-2.0";
    private static final int OJN_SIGNATURE = 0x006E6A6F;
    private static final int OJM_SIGNATURE = 0x004D4A4F;
    private static final int OMC_SIGNATURE = 0x00434D4F;
    private static final int M30_SIGNATURE = 0x0030334D;

    private MigrationGoldenFixtureFactory() {
    }

    enum Format {
        VOS,
        OJN_OJM,
        OSU_OSZ
    }

    enum Outcome {
        ACCEPT,
        REJECT
    }

    enum ErrorCode {
        UNSUPPORTED_FORMAT,
        CORRUPT_CHART,
        MISSING_COMPANION,
        MISSING_ASSET
    }

    record CaseDefinition(
            String id,
            Format format,
            String source,
            List<String> relatedFiles,
            List<String> coverage,
            Outcome expectedOutcome,
            ErrorCode expectedError,
            int minimumEvents,
            String provenance,
            String license) {
    }

    static List<CaseDefinition> definitions() {
        return List.of(
                accepted("vos-minimal", Format.VOS, "sources/vos/minimal.vos",
                        List.of(), List.of("minimal"), 1),
                accepted("vos-representative", Format.VOS, "sources/vos/canon.vos",
                        List.of(), List.of("representative", "long-note", "embedded-midi"), 2),
                accepted("vos-stress-4096", Format.VOS, "sources/vos/stress-4096.vos",
                        List.of(), List.of("stress"), 4096),
                accepted("vos-gb2312-title", Format.VOS, "sources/vos/gb2312-title.vos",
                        List.of(), List.of("encoding", "gb2312"), 1),
                accepted("vos-unicode-basename", Format.VOS, "sources/vos/曲目.vos",
                        List.of(), List.of("unicode", "basename"), 1),
                rejected("vos-truncated", Format.VOS, "sources/vos/truncated.vos",
                        List.of(), List.of("truncated"), ErrorCode.CORRUPT_CHART),
                rejected("vos-corrupt-header", Format.VOS, "sources/vos/corrupt-header.vos",
                        List.of(), List.of("malformed"), ErrorCode.CORRUPT_CHART),

                accepted("ojn-minimal-plain", Format.OJN_OJM, "sources/ojn/minimal.ojn",
                        List.of("sources/ojn/minimal.ojm"), List.of("minimal", "ojm-plain"), 0),
                accepted("ojn-representative-multi-chart", Format.OJN_OJM,
                        "sources/ojn/o2jam.ojn", List.of("sources/ojn/o2jam.ojm"),
                        List.of("representative", "multi-chart", "ojm-plain"), 0),
                accepted("ojn-stress-4096", Format.OJN_OJM,
                        "sources/ojn/stress-4096.ojn",
                        List.of("sources/ojn/stress-4096.ojm"), List.of("stress"), 4096),
                accepted("ojn-unicode-basename", Format.OJN_OJM, "sources/ojn/曲目.ojn",
                        List.of("sources/ojn/unicode.ojm"), List.of("encoding", "unicode", "basename"), 0),
                rejected("ojn-missing-companion", Format.OJN_OJM,
                        "sources/ojn/missing-companion.ojn",
                        List.of("sources/ojn/missing-companion.ojm"),
                        List.of("missing-companion"), ErrorCode.MISSING_COMPANION),
                rejected("ojn-truncated", Format.OJN_OJM, "sources/ojn/truncated.ojn",
                        List.of(), List.of("truncated"), ErrorCode.CORRUPT_CHART),
                rejected("ojn-corrupt-signature", Format.OJN_OJM,
                        "sources/ojn/corrupt-signature.ojn", List.of(),
                        List.of("malformed"), ErrorCode.CORRUPT_CHART),
                accepted("ojm-omc-encrypted", Format.OJN_OJM, "sources/ojn/omc.ojn",
                        List.of("sources/ojn/omc.ojm"),
                        List.of("omc", "encrypted", "17-block-rearrangement", "stateful-xor"), 0),
                accepted("ojm-m30-nami", Format.OJN_OJM, "sources/ojn/m30-nami.ojn",
                        List.of("sources/ojn/m30-nami.ojm"), List.of("m30", "nami-xor"), 0),
                accepted("ojm-m30-0412", Format.OJN_OJM, "sources/ojn/m30-0412.ojn",
                        List.of("sources/ojn/m30-0412.ojm"), List.of("m30", "0412-xor"), 0),

                accepted("osu-minimal", Format.OSU_OSZ, "sources/osu/minimal.osu",
                        List.of("sources/osu/minimal.wav"), List.of("minimal"), 1),
                accepted("osu-representative", Format.OSU_OSZ, "sources/osu/seven-key.osu",
                        List.of("sources/osu/audio.wav"),
                        List.of("representative", "long-note"), 8),
                accepted("osu-stress-4096", Format.OSU_OSZ, "sources/osu/stress-4096.osu",
                        List.of("sources/osu/stress.wav"), List.of("stress"), 4096),
                accepted("osu-unicode-basename", Format.OSU_OSZ, "sources/osu/曲目.osu",
                        List.of("sources/osu/音频.wav"),
                        List.of("encoding", "unicode", "basename"), 1),
                rejected("osu-missing-audio", Format.OSU_OSZ, "sources/osu/missing-audio.osu",
                        List.of("sources/osu/missing.wav"), List.of("missing-asset"),
                        ErrorCode.MISSING_ASSET),
                rejected("osu-non-mania", Format.OSU_OSZ, "sources/osu/non-mania.osu",
                        List.of(), List.of("unsupported-mode"), ErrorCode.UNSUPPORTED_FORMAT),
                rejected("osu-non-seven-key", Format.OSU_OSZ, "sources/osu/non-seven-key.osu",
                        List.of(), List.of("unsupported-key-count"), ErrorCode.UNSUPPORTED_FORMAT),
                rejected("osz-truncated", Format.OSU_OSZ, "sources/osu/truncated.osz",
                        List.of(), List.of("malformed", "truncated", "archive"),
                        ErrorCode.CORRUPT_CHART),
                accepted("osz-multi-chart", Format.OSU_OSZ, "sources/osu/multi-chart.osz",
                        List.of(), List.of("multi-chart", "archive-relative-asset", "inherited-timing"), 2),
                accepted("osz-case-insensitive-basename", Format.OSU_OSZ,
                        "sources/osu/case-insensitive.osz", List.of(),
                        List.of("osz", "case-insensitive-basename", "archive-relative-asset"), 1));
    }

    static void writeSources(Path sourcesRoot) throws Exception {
        writeVosSources(sourcesRoot.resolve("vos"));
        writeOjnSources(sourcesRoot.resolve("ojn"));
        writeOsuSources(sourcesRoot.resolve("osu"));
        writeLegacyMalformedSources(sourcesRoot.resolve("malformed"));
    }

    private static void writeVosSources(Path directory) throws Exception {
        Files.createDirectories(directory);
        VosFixtureFactory.writeFixture(
                directory.toFile(), "minimal.vos", 1, true, true, false, "Minimal VOS");
        VosFixtureFactory.writeFixture(
                directory.toFile(), "canon.vos", 7, true, true, true, "Canon in D");
        VosFixtureFactory.writeFixture(
                directory.toFile(), "stress-4096.vos", 12, true, true, false,
                "Stress VOS", 4096);
        VosFixtureFactory.writeFixture(
                directory.toFile(), "gb2312-title.vos", 5, true, true, false, "节奏测试");
        VosFixtureFactory.writeFixture(
                directory.toFile(), "曲目.vos", 6, true, true, false, "Unicode Basename");
        Files.write(directory.resolve("truncated.vos"), new byte[] {3, 0, 0, 0});
        Files.write(directory.resolve("corrupt-header.vos"), new byte[] {4, 0, 0, 0, 0, 0, 0, 0});
    }

    private static void writeOjnSources(Path directory) throws Exception {
        Files.createDirectories(directory);
        writeOjnPair(directory, "minimal", "minimal.ojm", OjmVariant.PLAIN, 0, "Minimal O2Jam");
        OjnFixtureFactory.writeFixture(directory.toFile(), "o2jam");
        writeOjnPair(directory, "stress-4096", "stress-4096.ojm", OjmVariant.PLAIN,
                4096, "O2Jam Stress");
        writeOjnPair(directory, "曲目", "unicode.ojm", OjmVariant.PLAIN, 0, "Unicode Basename");
        writeOjn(directory.resolve("missing-companion.ojn"), "missing-companion.ojm", 0,
                "Missing Companion");
        Files.write(directory.resolve("truncated.ojn"), new byte[] {1, 2, 3});
        byte[] corrupt = new byte[300];
        ByteBuffer.wrap(corrupt).order(ByteOrder.LITTLE_ENDIAN).putInt(100).putInt(0x12345678);
        Files.write(directory.resolve("corrupt-signature.ojn"), corrupt);
        writeOjnPair(directory, "omc", "omc.ojm", OjmVariant.OMC, 0, "Encrypted OMC");
        writeOjnPair(directory, "m30-nami", "m30-nami.ojm", OjmVariant.M30_NAMI, 0,
                "M30 Nami");
        writeOjnPair(directory, "m30-0412", "m30-0412.ojm", OjmVariant.M30_0412, 0,
                "M30 0412");
    }

    private static void writeOjnPair(
            Path directory,
            String baseName,
            String companionName,
            OjmVariant variant,
            int easyEventCount,
            String title) throws Exception {
        writeOjn(directory.resolve(baseName + ".ojn"), companionName, easyEventCount, title);
        Path companion = directory.resolve(companionName);
        if (variant == OjmVariant.PLAIN || variant == OjmVariant.OMC) {
            writeOmc(companion, variant == OjmVariant.OMC);
        } else {
            writeM30(companion, variant == OjmVariant.M30_NAMI ? 16 : 32);
        }
    }

    private static void writeOjn(
            Path chart, String companionName, int easyEventCount, String title) throws Exception {
        int noteBlockSize = easyEventCount == 0 ? 0 : 8 + easyEventCount * 4;
        int normalOffset = 300 + noteBlockSize;
        ByteBuffer buffer = ByteBuffer.allocate(normalOffset).order(ByteOrder.LITTLE_ENDIAN);
        buffer.putInt(100);
        buffer.putInt(OJN_SIGNATURE);
        buffer.putFloat(2.0f);
        buffer.putInt(2);
        buffer.putFloat(130.0f);
        buffer.putShort((short) 3);
        buffer.putShort((short) 5);
        buffer.putShort((short) 8);
        buffer.putShort((short) 0);
        buffer.putInt(easyEventCount);
        buffer.putInt(0);
        buffer.putInt(0);
        buffer.putInt(easyEventCount);
        buffer.putInt(0);
        buffer.putInt(0);
        buffer.putInt(easyEventCount == 0 ? 0 : 1);
        buffer.putInt(0);
        buffer.putInt(0);
        buffer.putInt(easyEventCount == 0 ? 0 : 1);
        buffer.putInt(0);
        buffer.putInt(0);
        buffer.putShort((short) 0);
        buffer.putShort((short) 0);
        putFixedAscii(buffer, "", 20);
        buffer.putInt(0);
        buffer.putInt(1);
        putFixedAscii(buffer, title, 64);
        putFixedAscii(buffer, "Fixture Artist", 32);
        putFixedAscii(buffer, "Fixture Noter", 32);
        putFixedAscii(buffer, companionName, 32);
        buffer.putInt(0);
        buffer.putInt(91);
        buffer.putInt(91);
        buffer.putInt(91);
        buffer.putInt(300);
        buffer.putInt(normalOffset);
        buffer.putInt(normalOffset);
        buffer.putInt(normalOffset);
        if (easyEventCount > 0) {
            buffer.putInt(0);
            buffer.putShort((short) 2);
            buffer.putShort((short) easyEventCount);
            for (int i = 0; i < easyEventCount; i++) {
                buffer.putShort((short) ((i % 7) + 1));
                buffer.put((byte) 0x88);
                buffer.put((byte) 0);
            }
        }
        Files.write(chart, buffer.array());
    }

    private static void writeOmc(Path path, boolean encrypted) throws Exception {
        byte[] pcm = new byte[34];
        for (int i = 0; i < pcm.length; i++) {
            pcm[i] = (byte) (i * 7 + 3);
        }
        int oggStart = 20 + 56 + pcm.length;
        ByteBuffer buffer = ByteBuffer.allocate(oggStart).order(ByteOrder.LITTLE_ENDIAN);
        buffer.putInt(encrypted ? OMC_SIGNATURE : OJM_SIGNATURE);
        buffer.putShort((short) 0);
        buffer.putShort((short) 0);
        buffer.putInt(20);
        buffer.putInt(oggStart);
        buffer.putInt(oggStart);
        putFixedAscii(buffer, "fixture.wav", 32);
        buffer.putShort((short) 1);
        buffer.putShort((short) 1);
        buffer.putInt(8000);
        buffer.putInt(16000);
        buffer.putShort((short) 2);
        buffer.putShort((short) 16);
        buffer.putInt(0x61746164);
        buffer.putInt(pcm.length);
        buffer.put(pcm);
        Files.write(path, buffer.array());
    }

    private static void writeM30(Path path, int encryptionFlag) throws Exception {
        byte[] sample = new byte[] {0, 1, 2, 3, 4, 5, 6, 7};
        ByteBuffer buffer = ByteBuffer.allocate(28 + 52 + sample.length)
                .order(ByteOrder.LITTLE_ENDIAN);
        buffer.putInt(M30_SIGNATURE);
        buffer.putInt(1);
        buffer.putInt(encryptionFlag);
        buffer.putInt(1);
        buffer.putInt(28);
        buffer.putInt(52 + sample.length);
        buffer.putInt(0);
        putFixedAscii(buffer, "fixture.ogg", 32);
        buffer.putInt(sample.length);
        buffer.putShort((short) 5);
        buffer.putShort((short) 0);
        buffer.putInt(0);
        buffer.putShort((short) 1);
        buffer.putShort((short) 0);
        buffer.putInt(0);
        buffer.put(sample);
        Files.write(path, buffer.array());
    }

    private static void writeOsuSources(Path directory) throws Exception {
        Files.createDirectories(directory);
        writeWav(directory.resolve("minimal.wav"));
        writeUtf8(directory.resolve("minimal.osu"), osuContent(
                "minimal.wav", "Minimal Mania", 3, 7, 1, false, false));

        OsuFixtureFactory.writeSevenKeyOsu(directory.toFile(), "seven-key.osu");
        writeWav(directory.resolve("stress.wav"));
        writeUtf8(directory.resolve("stress-4096.osu"), osuContent(
                "stress.wav", "Stress Mania", 3, 7, 4096, false, false));

        writeWav(directory.resolve("音频.wav"));
        writeUtf8(directory.resolve("曲目.osu"), osuContent(
                "音频.wav", "节奏测试", 3, 7, 1, false, false));
        writeUtf8(directory.resolve("missing-audio.osu"), osuContent(
                "missing.wav", "Missing Audio", 3, 7, 1, false, false));
        writeUtf8(directory.resolve("non-mania.osu"), osuContent(
                "", "Unsupported Mode", 0, 7, 1, false, false));
        writeUtf8(directory.resolve("non-seven-key.osu"), osuContent(
                "", "Unsupported Keys", 3, 4, 1, false, false));
        Files.write(directory.resolve("truncated.osz"), new byte[] {'P', 'K', 3, 4, 1, 2, 3});
        writeMultiChartOsz(directory.resolve("multi-chart.osz"));
        OsuFixtureFactory.writeSevenKeyOsz(directory.toFile(), "seven-key.osz");
        writeCaseInsensitiveOsz(directory.resolve("case-insensitive.osz"));
    }

    private static void writeLegacyMalformedSources(Path directory) throws Exception {
        Files.createDirectories(directory);
        Files.write(directory.resolve("truncated.vos"), new byte[] {3, 0, 0, 0});
        Files.write(directory.resolve("truncated.ojn"), new byte[] {1, 2, 3});
        writeUtf8(
                directory.resolve("non-mania.osu"),
                OsuFixtureFactory.sevenKeyContent("audio.wav").replace("Mode: 3", "Mode: 0"));
    }

    private static String osuContent(
            String audioFilename,
            String title,
            int mode,
            int keys,
            int noteCount,
            boolean inheritedTiming,
            boolean customHitsound) {
        StringBuilder content = new StringBuilder();
        content.append("osu file format v14\n\n")
                .append("[General]\nAudioFilename:");
        if (!audioFilename.isEmpty()) {
            content.append(' ').append(audioFilename);
        }
        content.append("\nMode: ").append(mode).append("\n\n")
                .append("[Metadata]\nTitle:").append(title)
                .append("\nTitleUnicode:").append(title)
                .append("\nArtist:Fixture Artist\nCreator:Fixture Creator\nVersion:Test 7K\n\n")
                .append("[Difficulty]\nHPDrainRate:5\nCircleSize:").append(keys)
                .append("\nOverallDifficulty:8\n\n")
                .append("[TimingPoints]\n0,500,4,2,1,60,1,0\n");
        if (inheritedTiming) {
            content.append("1000,-50,4,2,1,60,0,0\n");
        }
        content.append("\n[HitObjects]\n");
        for (int i = 0; i < noteCount; i++) {
            int lane = i % 7;
            int x = 36 + lane * 73;
            int time = i * 2;
            if (customHitsound && i == 0) {
                content.append(x).append(",192,").append(time)
                        .append(",1,0,0:0:0:100:hit.wav\n");
            } else {
                content.append(x).append(",192,").append(time)
                        .append(",1,0,0:0:0:0:\n");
            }
        }
        return content.toString();
    }

    private static void writeMultiChartOsz(Path archive) throws Exception {
        try (ZipOutputStream zip = new ZipOutputStream(Files.newOutputStream(archive))) {
            writeZipEntry(zip, "pack/audio.wav", silentWav());
            writeZipEntry(zip, "pack/easy.osu", osuContent(
                    "audio.wav", "Archive Multi", 3, 7, 1, false, false)
                    .getBytes(StandardCharsets.UTF_8));
            writeZipEntry(zip, "pack/hard.osu", osuContent(
                    "audio.wav", "Archive Multi", 3, 7, 1, true, false)
                    .getBytes(StandardCharsets.UTF_8));
        }
    }

    private static void writeCaseInsensitiveOsz(Path archive) throws Exception {
        try (ZipOutputStream zip = new ZipOutputStream(Files.newOutputStream(archive))) {
            writeZipEntry(zip, "assets/audio.wav", silentWav());
            writeZipEntry(zip, "nested/seven-key.osu", osuContent(
                    "AUDIO.WAV", "Archive Basename", 3, 7, 1, true, false)
                    .getBytes(StandardCharsets.UTF_8));
        }
    }

    private static void writeZipEntry(ZipOutputStream zip, String name, byte[] bytes)
            throws Exception {
        ZipEntry entry = new ZipEntry(name);
        entry.setTime(0L);
        zip.putNextEntry(entry);
        zip.write(bytes);
        zip.closeEntry();
    }

    private static void writeWav(Path path) throws Exception {
        Files.write(path, silentWav());
    }

    private static byte[] silentWav() {
        return new byte[] {
                'R', 'I', 'F', 'F', 38, 0, 0, 0, 'W', 'A', 'V', 'E',
                'f', 'm', 't', ' ', 16, 0, 0, 0, 1, 0, 1, 0,
                64, 31, 0, 0, -128, 62, 0, 0, 2, 0, 16, 0,
                'd', 'a', 't', 'a', 2, 0, 0, 0, 0, 0
        };
    }

    private static void writeUtf8(Path path, String content) throws Exception {
        Files.writeString(path, content, StandardCharsets.UTF_8);
    }

    private static void putFixedAscii(ByteBuffer buffer, String value, int length) {
        byte[] bytes = value.getBytes(StandardCharsets.US_ASCII);
        int written = Math.min(bytes.length, length);
        buffer.put(bytes, 0, written);
        for (int i = written; i < length; i++) {
            buffer.put((byte) 0);
        }
    }

    private static CaseDefinition accepted(
            String id,
            Format format,
            String source,
            List<String> relatedFiles,
            List<String> coverage,
            int minimumEvents) {
        return new CaseDefinition(
                id, format, source, List.copyOf(relatedFiles), List.copyOf(coverage),
                Outcome.ACCEPT, null, minimumEvents, PROVENANCE, LICENSE);
    }

    private static CaseDefinition rejected(
            String id,
            Format format,
            String source,
            List<String> relatedFiles,
            List<String> coverage,
            ErrorCode expectedError) {
        return new CaseDefinition(
                id, format, source, List.copyOf(relatedFiles), List.copyOf(coverage),
                Outcome.REJECT, expectedError, 0, PROVENANCE, LICENSE);
    }

    private enum OjmVariant {
        PLAIN,
        OMC,
        M30_NAMI,
        M30_0412
    }
}
