/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package org.open2jam.gui.parts;

import javax.swing.GroupLayout;
import javax.swing.LayoutStyle;
import org.open2jam.Config;
import org.open2jam.GameOptions;

/**
 *
 * @author Thai Pangsakulyanont
 */
public class AdvancedOptions extends javax.swing.JPanel {

    /**
     * Creates new form AdvancedSettings
     */
    public AdvancedOptions() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        go = Config.getGameOptions()
        ;
        hasteModeCheckbox = new javax.swing.JCheckBox();
        bufferSize = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jCheckBox1 = new javax.swing.JCheckBox();

        hasteModeCheckbox.setText("Haste Mode");
        hasteModeCheckbox.setSelected(go.isHasteMode());

        hasteModeCheckbox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hasteModeCheckboxActionPerformed(evt);
            }
        });

        bufferSize.setText(Integer.toString(go.getBufferSize()));

        bufferSize.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bufferSizeActionPerformed(evt);
            }
        });
        bufferSize.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                bufferSizeFocusLost(evt);
            }
        });

        jLabel1.setText("Buffer Size");

        jCheckBox1.setText("Normalize Speed");
        jCheckBox1.setSelected(go.isHasteModeNormalizeSpeed());
        jCheckBox1.setEnabled(go.isHasteMode());
        jCheckBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                normalizeSpeedCheckboxActionPerformed(evt);
            }
        });

        GroupLayout layout = new GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(47, 47, 47)
                .addGroup(layout.createParallelGroup(GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(hasteModeCheckbox)
                        .addPreferredGap(LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jCheckBox1))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(bufferSize, GroupLayout.PREFERRED_SIZE, 56, GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel1)))
                .addContainerGap(330, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(GroupLayout.Alignment.BASELINE)
                    .addComponent(hasteModeCheckbox)
                    .addComponent(jCheckBox1))
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(GroupLayout.Alignment.BASELINE)
                    .addComponent(bufferSize, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addContainerGap(296, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void hasteModeCheckboxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hasteModeCheckboxActionPerformed
        go.setHasteMode(hasteModeCheckbox.isSelected());
        jCheckBox1.setEnabled(go.isHasteMode());
    }//GEN-LAST:event_hasteModeCheckboxActionPerformed

    private void bufferSizeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bufferSizeActionPerformed
        updateBufferSize();
    }//GEN-LAST:event_bufferSizeActionPerformed

    private void bufferSizeFocusLost(java.awt.event.FocusEvent evt) {
        updateBufferSize();
    }

    private void normalizeSpeedCheckboxActionPerformed(java.awt.event.ActionEvent evt) {
        go.setHasteModeNormalizeSpeed(jCheckBox1.isSelected());
    }

    private void updateBufferSize() {
        try {
            go.setBufferSize(Integer.parseInt(bufferSize.getText().trim()));
        } catch (NumberFormatException e) {
            bufferSize.setText(Integer.toString(go.getBufferSize()));
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField bufferSize;
    private org.open2jam.GameOptions go;
    private javax.swing.JCheckBox hasteModeCheckbox;
    private javax.swing.JCheckBox jCheckBox1;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
