#!/usr/bin/env bash
set -euo pipefail

ROOT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/../.." && pwd)"
cd "$ROOT_DIR"

INITIAL_VERIFIER="rewrite/tools/verify_vos_godot_initial.sh"
JAVA_CAPTURE_SCRIPT="rewrite/tools/capture_java_gameplay_screenshot.sh"
PAIR_CAPTURE_SCRIPT="rewrite/tools/capture_gameplay_parity_pair.sh"
RECORDED_CAPTURE_SCRIPT="rewrite/tools/capture_recorded_gameplay_parity_summaries.sh"
SUMMARY_VERIFIER_SCRIPT="rewrite/tools/verify_gameplay_parity_summary.sh"
SUMMARY_VERIFIER_TEST="rewrite/tools/test_verify_gameplay_parity_summary.sh"
CAPTURE_CONTRACT_TEST="rewrite/tools/test_gameplay_parity_capture_contract.sh"
MANUAL_ACCEPTANCE="docs/rewrite/godot-java-parity-manual-acceptance.md"
MANUAL_ACCEPTANCE_REPORT="docs/rewrite/godot-java-parity-manual-acceptance-report.md"
REQUIRE_RECORDED_SUMMARIES="${OPEN2JAM_RECORDED_PARITY_REQUIRE_ALL:-0}"
GAMEPLAY_FIXTURE="rewrite/godot/test/fixtures/gameplay.json"
AUDIO_FIXTURE="rewrite/godot/test/fixtures/audio-manifest.json"
RENDER_FIXTURE="rewrite/godot/test/fixtures/render-metadata.json"
LONG_NOTE_RELEASE_FIXTURE="rewrite/godot/test/fixtures/long-note-release-oracle.json"
BGA_EVENT_FIXTURE="rewrite/godot/test/fixtures/bga-event-oracle.json"
MEASURE_EVENT_FIXTURE="rewrite/godot/test/fixtures/measure-event-oracle.json"
FPS_TIMER_FIXTURE="rewrite/godot/test/fixtures/fps-timer-oracle.json"
NOTE_DISTANCE_FIXTURE="rewrite/godot/test/fixtures/note-distance-oracle.json"
SPEED_MULTIPLIER_FIXTURE="rewrite/godot/test/fixtures/speed-multiplier-oracle.json"
MISC_VOLUME_FIXTURE="rewrite/godot/test/fixtures/misc-volume-oracle.json"
QUEUE_SAMPLE_FIXTURE="rewrite/godot/test/fixtures/queue-sample-oracle.json"
LATENCY_FIXTURE="rewrite/godot/test/fixtures/latency-oracle.json"
RECORDED_SAME_CHART_SUMMARY="target/gameplay-parity-capture/summary.json"
RECORDED_SAME_CHART_DIFF_COMPONENTS="target/gameplay-parity-capture/diff-components.json"
RECORDED_REAL_DEMO_SUMMARY="target/gameplay-parity-capture-real-demo/summary.json"
RECORDED_REAL_DEMO_DIFF_COMPONENTS="target/gameplay-parity-capture-real-demo/diff-components.json"
RECORDED_REAL_OJN_SUMMARY="target/gameplay-parity-capture-real-ojn-notes/summary.json"
RECORDED_REAL_OJN_DIFF_COMPONENTS="target/gameplay-parity-capture-real-ojn-notes/diff-components.json"
RECORDED_REAL_OSU_SUMMARY="target/gameplay-parity-capture-real-osu-notes/summary.json"
RECORDED_REAL_OSU_DIFF_COMPONENTS="target/gameplay-parity-capture-real-osu-notes/diff-components.json"

require_file() {
	local path="$1"
	if [[ ! -f "$path" ]]; then
		printf 'Missing required file: %s\n' "$path" >&2
		exit 1
	fi
}

require_text() {
	local path="$1"
	local text="$2"
	local label="$3"
	if ! grep -Fq -- "$text" "$path"; then
		printf 'Missing %s in %s\n' "$label" "$path" >&2
		exit 1
	fi
}

verify_recorded_summary() {
	local label="$1"
	local summary_path="$2"
	local diff_components_path="$3"
	local pixel_tolerance="$4"

	if [[ ! -f "$summary_path" && ! -f "$diff_components_path" ]]; then
		if [[ "$REQUIRE_RECORDED_SUMMARIES" == "1" ]]; then
			printf 'Missing recorded %s summary artifacts: %s and %s\n' \
				"$label" "$summary_path" "$diff_components_path" >&2
			exit 1
		fi
		printf 'Skipping recorded %s summary verification; artifacts are not present.\n' "$label"
		return
	fi

	require_file "$summary_path"
	require_file "$diff_components_path"
	printf 'Verifying recorded %s summary.\n' "$label"
	OPEN2JAM_PARITY_PIXEL_TOLERANCE="$pixel_tolerance" \
		bash "$SUMMARY_VERIFIER_SCRIPT" "$summary_path" "$diff_components_path"
}

require_file "$INITIAL_VERIFIER"
require_file "$JAVA_CAPTURE_SCRIPT"
require_file "$PAIR_CAPTURE_SCRIPT"
require_file "$RECORDED_CAPTURE_SCRIPT"
require_file "$SUMMARY_VERIFIER_SCRIPT"
require_file "$SUMMARY_VERIFIER_TEST"
require_file "$CAPTURE_CONTRACT_TEST"
require_file "$MANUAL_ACCEPTANCE"
require_file "$MANUAL_ACCEPTANCE_REPORT"
require_file "$GAMEPLAY_FIXTURE"
require_file "$AUDIO_FIXTURE"
require_file "$RENDER_FIXTURE"
require_file "$LONG_NOTE_RELEASE_FIXTURE"
require_file "$BGA_EVENT_FIXTURE"
require_file "$MEASURE_EVENT_FIXTURE"
require_file "$FPS_TIMER_FIXTURE"
require_file "$NOTE_DISTANCE_FIXTURE"
require_file "$SPEED_MULTIPLIER_FIXTURE"
require_file "$MISC_VOLUME_FIXTURE"
require_file "$QUEUE_SAMPLE_FIXTURE"
require_file "$LATENCY_FIXTURE"

require_text "$INITIAL_VERIFIER" 'LWJGLGameWindowTest' "Java capture window test"
require_text "$INITIAL_VERIFIER" 'JAVA_TESTS=(' "Java test list array"
require_text "$INITIAL_VERIFIER" 'java_tests_csv="$(IFS=,; printf' "Java test CSV construction"
require_text "$INITIAL_VERIFIER" 'mvn -s "${MAVEN_SETTINGS:-.mvn/settings.xml}" -Dtest="$java_tests_csv" test' "Maven settings-backed Java verifier command"
require_text "$INITIAL_VERIFIER" 'java_capture_viewport_config_test.gd' "Java capture viewport config test"
require_text "$INITIAL_VERIFIER" 'selected_export_job_test.gd' "selected export async job test"
require_text "$INITIAL_VERIFIER" 'RenderMeasureEventOracleFixtureTest' "Java measure event oracle test"
require_text "$INITIAL_VERIFIER" 'gameplay_measure_event_java_oracle_test.gd' "Godot measure event oracle test"
require_text "$INITIAL_VERIFIER" 'RenderMiscVolumeOracleFixtureTest' "Java misc volume oracle test"
require_text "$INITIAL_VERIFIER" 'misc_volume_java_oracle_test.gd' "Godot misc volume oracle test"
require_text "$INITIAL_VERIFIER" 'RenderQueueSampleOracleFixtureTest' "Java queue sample oracle test"
require_text "$INITIAL_VERIFIER" 'queue_sample_java_oracle_test.gd' "Godot queue sample oracle test"
require_text "$PAIR_CAPTURE_SCRIPT" 'OPEN2JAM_PARITY_CAPTURE_MIN_JAVA_IMAGE_BYTES' "Java blank capture guard"
require_text "$PAIR_CAPTURE_SCRIPT" '-Djava.awt.headless=true' "headless Java screenshot compare"
require_text "$PAIR_CAPTURE_SCRIPT" 'verify_gameplay_parity_summary.sh' "same-chart summary threshold verification"
require_text "$RECORDED_CAPTURE_SCRIPT" 'target/gameplay-parity-capture' "recorded same-chart VOS capture output"
require_text "$RECORDED_CAPTURE_SCRIPT" 'target/gameplay-parity-capture-real-demo' "recorded real demo VOS capture output"
require_text "$RECORDED_CAPTURE_SCRIPT" 'target/gameplay-parity-capture-real-ojn-notes' "recorded real OJN capture output"
require_text "$RECORDED_CAPTURE_SCRIPT" 'target/gameplay-parity-capture-real-osu-notes' "recorded real OSU capture output"
require_text "$RECORDED_CAPTURE_SCRIPT" 'OPEN2JAM_PARITY_COMPARE_PIXEL_TOLERANCE="$pixel_tolerance"' "recorded capture pixel tolerance propagation"
require_text "$SUMMARY_VERIFIER_SCRIPT" 'OPEN2JAM_PARITY_MAX_DIFFERING_PIXELS' "differing pixel threshold"
require_text "$SUMMARY_VERIFIER_SCRIPT" 'OPEN2JAM_PARITY_MAX_LARGEST_COMPONENT_PIXELS' "largest component threshold"
require_text "$SUMMARY_VERIFIER_SCRIPT" 'OPEN2JAM_PARITY_MAX_LARGEST_COMPONENT_SHORT_SIDE' "largest component short-side threshold"
require_text "$RENDER_FIXTURE" '"format":"VOS_RENDER_METADATA"' "render metadata format marker"
require_text "$RENDER_FIXTURE" '"visibilityLayer":7' "visibility layer metadata"
require_text "$RENDER_FIXTURE" '"visibilityMasks"' "visibility mask metadata"
require_text "$RENDER_FIXTURE" '"Hidden":[{"at":0.0,"alpha":0.0},{"at":1.9,"alpha":0.0},{"at":2.0,"alpha":1.0},{"at":4.0,"alpha":1.0}]' "hidden visibility mask metadata"
require_text "$RENDER_FIXTURE" '"Dark":[{"at":0.0,"alpha":1.0},{"at":1.3,"alpha":1.0},{"at":1.5,"alpha":0.0},{"at":2.5,"alpha":0.0},{"at":2.7,"alpha":1.0},{"at":4.0,"alpha":1.0}]' "dark visibility mask metadata"
require_text "$RENDER_FIXTURE" '"statusTextLayout"' "status text layout metadata"
require_text "$RENDER_FIXTURE" '"rightX":780.0' "status text right-x metadata"
require_text "$RENDER_FIXTURE" '"startY":300.0' "status text start-y metadata"
require_text "$RENDER_FIXTURE" '"lineHeight":30.0' "status text line-height metadata"
require_text "$RENDER_FIXTURE" '"fontSize":14' "status text font-size metadata"
require_text "$RENDER_FIXTURE" '"glyphHeight":20.0' "status text glyph-height metadata"
require_text "$RENDER_FIXTURE" '"antiAlias":false' "status text antialias metadata"
require_text "$RENDER_FIXTURE" '"fontColor":"#ffffffff"' "status text font color metadata"
require_text "$RENDER_FIXTURE" '"scaleY":-1.0' "status text scale-y metadata"
require_text "$RENDER_FIXTURE" '"startY":64.0' "network status text start-y metadata"
require_text "$RENDER_FIXTURE" '"serverLineHeight":24.0' "network status server line-height metadata"
require_text "$RENDER_FIXTURE" '"connectionLineHeight":18.0' "network status connection line-height metadata"
require_text "$RENDER_FIXTURE" '"statusTextTemplates"' "status text templates metadata"
require_text "$RENDER_FIXTURE" '"speed":"{speedType}: x{speedMultiplier}"' "speed status text template"
require_text "$RENDER_FIXTURE" '"gameSpeed":"Game Speed: {gameSpeedPitch}"' "game speed status text template"
require_text "$RENDER_FIXTURE" '"RegulSpeed":"REGUL-SPEED"' "regul speed status label"
require_text "$RENDER_FIXTURE" '"statusFont":{"source":"TrueTypeFont"' "status font metadata"
require_text "$RENDER_FIXTURE" '"textureWidth":512' "status font texture width"
require_text "$RENDER_FIXTURE" '"textureHeight":512' "status font texture height"
require_text "$RENDER_FIXTURE" '"correctL":9' "status font left correction"
require_text "$RENDER_FIXTURE" '"correctR":8' "status font right correction"
require_text "$RENDER_FIXTURE" '"pngBase64"' "status font atlas png"
require_text "$RENDER_FIXTURE" '"id":"JUDGMENT_LINE"' "judgment line entity"
require_text "$RENDER_FIXTURE" '"id":"COMBO_COUNTER"' "combo counter entity"
require_text "$RENDER_FIXTURE" '"id":"SCORE_COUNTER"' "score counter entity"
require_text "$RENDER_FIXTURE" '"id":"LIFE_BAR"' "life bar entity"
require_text "$RENDER_FIXTURE" '"id":"","type":"entity","layer":1,"x":226.0,"y":515.0,"width":226.0,"height":72.0,"named":false' "static timebar entity"
require_text "$RENDER_FIXTURE" '"sprites":["timebar"]' "static timebar sprite"
require_text "$RENDER_FIXTURE" '"id":"EFFECT_CLICK"' "click effect entity"
require_text "$RENDER_FIXTURE" '"id":"EFFECT_JUDGMENT_COOL"' "judgment effect entity"
require_text "$RENDER_FIXTURE" '"id":"EFFECT_LONGFLARE"' "long flare entity"
require_text "$RENDER_FIXTURE" '"animationLoop":false' "click effect one-shot animation metadata"
require_text "$RENDER_FIXTURE" '"animationLoop":true' "looping animation metadata"
require_text "$RENDER_FIXTURE" '"countThreshold":2' "combo counter threshold metadata"
require_text "$RENDER_FIXTURE" '"countThreshold":1' "jam counter threshold metadata"
require_text "$RENDER_FIXTURE" '"showTimeMs":4000.0' "combo counter show-time metadata"
require_text "$RENDER_FIXTURE" '"wobblePixels":10.0' "combo counter wobble metadata"
require_text "$RENDER_FIXTURE" '"wobbleSpeed":0.5' "combo counter wobble speed metadata"
require_text "$RENDER_FIXTURE" '"showTimeMs":3000.0' "judgment effect show-time metadata"
require_text "$RENDER_FIXTURE" '"scaleRampMs":100.0' "judgment effect scale-ramp metadata"
require_text "$RENDER_FIXTURE" '"initialScale":0.5' "judgment effect initial-scale metadata"
require_text "$GAMEPLAY_FIXTURE" '"judgmentTiming"' "judgment timing export"
require_text "$GAMEPLAY_FIXTURE" '"visualTiming"' "visual timing export"
require_text "$GAMEPLAY_FIXTURE" '"autoPlayEvents"' "autoplay export"
require_text "$AUDIO_FIXTURE" '"assets"' "audio asset manifest"
require_text "$LONG_NOTE_RELEASE_FIXTURE" '"source":"Render.check_keyboard release with Render.check_judgment JUDGE"' "long note release oracle source"
require_text "$LONG_NOTE_RELEASE_FIXTURE" '"tail_early_miss"' "long note early release miss oracle"
require_text "$LONG_NOTE_RELEASE_FIXTURE" '"tail_late_bad"' "long note late release bad oracle"
require_text "$BGA_EVENT_FIXTURE" '"source":"Render TimeEntity loop for BgaEntity"' "BGA event oracle source"
require_text "$BGA_EVENT_FIXTURE" '"autosound_latency"' "BGA autosound latency oracle"
require_text "$BGA_EVENT_FIXTURE" '"queued_same_frame"' "BGA queued same-frame oracle"
require_text "$MEASURE_EVENT_FIXTURE" '"source":"Render TimeEntity loop for MeasureEntity"' "measure event oracle source"
require_text "$MEASURE_EVENT_FIXTURE" '"autosound_latency"' "measure autosound latency oracle"
require_text "$MEASURE_EVENT_FIXTURE" '"timeToJudgeMs":1000.0' "measure SoundEntity latency cancellation oracle"
require_text "$FPS_TIMER_FIXTURE" '"source":"Render.update_fps_counter"' "FPS timer oracle source"
require_text "$FPS_TIMER_FIXTURE" '"one_minute_rollover"' "FPS timer minute rollover oracle"
require_text "$FPS_TIMER_FIXTURE" '"large_delta_single_tick"' "FPS timer large delta oracle"
require_text "$NOTE_DISTANCE_FIXTURE" '"source":"NoteDistanceCalculator Java speed modes"' "note distance oracle source"
require_text "$NOTE_DISTANCE_FIXTURE" '"hi_speed_basic"' "hi speed distance oracle"
require_text "$NOTE_DISTANCE_FIXTURE" '"regul_speed_fixed_bpm"' "regul speed distance oracle"
require_text "$NOTE_DISTANCE_FIXTURE" '"w_speed_cycle_uses_target_speed"' "w speed target-speed oracle"
require_text "$NOTE_DISTANCE_FIXTURE" '"xr_speed_lane_seven"' "xr speed lane oracle"
require_text "$SPEED_MULTIPLIER_FIXTURE" '"source":"SpeedMultiplier Java update behavior"' "speed multiplier oracle source"
require_text "$SPEED_MULTIPLIER_FIXTURE" '"smooth_increase_and_decrease"' "speed multiplier smoothing oracle"
require_text "$SPEED_MULTIPLIER_FIXTURE" '"upper_clamp"' "speed multiplier upper clamp oracle"
require_text "$SPEED_MULTIPLIER_FIXTURE" '"lower_clamp"' "speed multiplier lower clamp oracle"
require_text "$MISC_VOLUME_FIXTURE" '"source":"Render.check_misc_keyboard volume hotkeys"' "misc volume oracle source"
require_text "$MISC_VOLUME_FIXTURE" '"master_volume_held_key"' "misc volume held-key oracle"
require_text "$MISC_VOLUME_FIXTURE" '"volume_channel_clamps"' "misc volume clamp oracle"
require_text "$MISC_VOLUME_FIXTURE" '"initial_volume_clamps"' "misc volume initial clamp oracle"
require_text "$QUEUE_SAMPLE_FIXTURE" '"source":"Render.queueSample playback parameters"' "queue sample oracle source"
require_text "$QUEUE_SAMPLE_FIXTURE" '"key_sample_ignores_volume"' "queue sample ignores volume oracle"
require_text "$QUEUE_SAMPLE_FIXTURE" '"bgm_sample_raw_pan"' "queue sample raw pan oracle"
require_text "$QUEUE_SAMPLE_FIXTURE" '"playVolume":1.0' "queue sample play volume oracle"
require_text "$QUEUE_SAMPLE_FIXTURE" '"playPan":1.25' "queue sample raw pan value oracle"
require_text "$LATENCY_FIXTURE" '"source":"Latency.autosync"' "latency oracle source"
require_text "$LATENCY_FIXTURE" '"historySize":64' "latency history size"
require_text "$LATENCY_FIXTURE" '"positive_start"' "latency positive-start oracle"
require_text "$LATENCY_FIXTURE" '"negative_start"' "latency negative-start oracle"

require_text "$MANUAL_ACCEPTANCE" 'Fullscreen layout' "fullscreen acceptance item"
require_text "$MANUAL_ACCEPTANCE" 'Settings and key bindings' "settings acceptance item"
require_text "$MANUAL_ACCEPTANCE" 'Song select' "song select acceptance item"
require_text "$MANUAL_ACCEPTANCE" 'Gameplay Java parity' "gameplay acceptance item"
require_text "$MANUAL_ACCEPTANCE" 'Result, retry, and back flow' "result flow acceptance item"
require_text "$MANUAL_ACCEPTANCE" 'VOS, OJN/OJM, 和 osu!mania 7K charts' "multi-format song select acceptance item"
require_text "$MANUAL_ACCEPTANCE" 'godot-java-parity-manual-acceptance-report.md' "manual acceptance report link"
require_text "$MANUAL_ACCEPTANCE" 'capture_java_gameplay_screenshot.sh' "Java capture command"
require_text "$MANUAL_ACCEPTANCE" 'capture_gameplay_parity_pair.sh' "same-chart parity capture command"
require_text "$MANUAL_ACCEPTANCE_REPORT" 'Accepted with bounded residual visual difference' "manual acceptance bounded residual decision"
require_text "$MANUAL_ACCEPTANCE_REPORT" 'VOS, OJN/OJM, and osu!mania 7K recorded screenshot packages' "multi-format report scope"
require_text "$MANUAL_ACCEPTANCE_REPORT" 'OJN/OJM chart path:' "OJN/OJM evidence path"
require_text "$MANUAL_ACCEPTANCE_REPORT" 'osu!mania 7K chart path:' "osu!mania evidence path"
require_text "$MANUAL_ACCEPTANCE_REPORT" 'target/godot-captures/godot-gameplay-fixture.png' "Godot screenshot evidence path"
require_text "$MANUAL_ACCEPTANCE_REPORT" 'target/java-captures/java-gameplay-reference.png' "Java screenshot evidence path"
require_text "$MANUAL_ACCEPTANCE_REPORT" 'target/gameplay-parity-capture/side-by-side.png' "side-by-side evidence path"
require_text "$MANUAL_ACCEPTANCE_REPORT" 'target/gameplay-parity-capture/diff.png' "diff evidence path"
require_text "$MANUAL_ACCEPTANCE_REPORT" 'target/gameplay-parity-capture/diff-components.json' "diff components evidence path"
require_text "$MANUAL_ACCEPTANCE_REPORT" 'target/gameplay-parity-capture/summary.json' "comparison summary evidence path"
require_text "$MANUAL_ACCEPTANCE_REPORT" 'target/gameplay-parity-capture-real-demo/diff-components.json' "real demo diff components evidence path"
require_text "$MANUAL_ACCEPTANCE_REPORT" 'target/gameplay-parity-capture-real-ojn-notes/summary.json' "real OJN summary evidence path"
require_text "$MANUAL_ACCEPTANCE_REPORT" 'target/gameplay-parity-capture-real-osu-notes/summary.json' "real OSU summary evidence path"
require_text "$MANUAL_ACCEPTANCE_REPORT" 'OPEN2JAM_RECORDED_PARITY_REQUIRE_ALL=1 rewrite/tools/capture_recorded_gameplay_parity_summaries.sh' "recorded summary require-all refresh command"
require_text "$MANUAL_ACCEPTANCE_REPORT" 'target/capture-recorded-gameplay-parity-require-all.log' "recorded summary refresh log"
require_text "$MANUAL_ACCEPTANCE_REPORT" 'pixelTolerance=4' "real OSU renderer rounding tolerance"
require_text "$MANUAL_ACCEPTANCE_REPORT" 'significantDifferingPixels=200' "real OSU significant diff summary"
require_text "$MANUAL_ACCEPTANCE_REPORT" 'x=385,y=569,width=23,height=1,pixels=23' "largest diff component summary"

bash "$SUMMARY_VERIFIER_TEST"
bash "$CAPTURE_CONTRACT_TEST"
verify_recorded_summary "same-chart VOS" "$RECORDED_SAME_CHART_SUMMARY" "$RECORDED_SAME_CHART_DIFF_COMPONENTS" 0
verify_recorded_summary "real demo VOS" "$RECORDED_REAL_DEMO_SUMMARY" "$RECORDED_REAL_DEMO_DIFF_COMPONENTS" 0
verify_recorded_summary "real OJN note-time" "$RECORDED_REAL_OJN_SUMMARY" "$RECORDED_REAL_OJN_DIFF_COMPONENTS" 0
verify_recorded_summary "real OSU long-note" "$RECORDED_REAL_OSU_SUMMARY" "$RECORDED_REAL_OSU_DIFF_COMPONENTS" 4
bash "$INITIAL_VERIFIER"

cat <<'EOF'
Automated VOS Godot Java parity gate passed.
Manual residual review is recorded as accepted with bounded residual visual difference:
  docs/rewrite/godot-java-parity-manual-acceptance.md
EOF
